### PR TITLE
 Import PreExecutionError in no_std and fix documentation misplacement 

### LINKED ISSUE #302: Building without std and PreExecutionError
It seems that disabling the `std` feature causes some issues with `PreExecutionError` not being imported in `transaction.rs`. The import seems to be behind `#[cfg(feature = "std")]` for some reason, which breaks the rest of the code expecting `PreExecutionError` to be available.

I don't see any reason why `PreExecutionError` should not work without `std` (in fact I tested it in an environment without std and it does seem to work).

### PR DESCRIPTION
**Pull request by sorpaas**
Fix #302

### CODE REVIEW

File: src/transaction.rs [hunk 1]
```diff
@@ -15,7 +15,6 @@ use alloc::Vec;
 use bigint::{U256, H256, Address, Gas};
 
 use super::errors::{RequireError, CommitError};
-#[cfg(feature = "std")]
 use super::errors::PreExecutionError;
```
Comment (kostko) [inline src/transaction.rs]: You could also move `PreExecutionError` to above errors import.

Comment (sorpaas) [reply src/transaction.rs]: Oops, right. Thanks!

**Comment by sorpaas** [comment]
@ethereumproject/etcdev-team Please review. Thanks!

**Review by whilei — APPROVED** [review]
